name: videosdk_flutter_example
description: A Flutter project for VideoSDK Demonstration.

publish_to: "none"

version: 1.0.0+14
environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  videosdk: 1.1.12
  http: ^1.1.0
  flutter_dotenv: ^5.0.2
  flutter_svg: ^2.0.2
  date_time_format: ^2.0.1
  touch_ripple_effect: ^2.2.3
  lottie: ^2.2.0
  responsive_framework: 1.1.1
  window_manager: ^0.3.4

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env
