name: videosdk_flutter_example
description: A Flutter project for VideoSDK Demonstration.

publish_to: "none"

version: 1.0.0+11
environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  videosdk: ^1.0.10
  http: ^0.13.5
  flutter_dotenv: ^5.0.2
  camera: ^0.10.0
  flutter_svg: ^1.1.5
  date_time_format: ^2.0.1
  touch_ripple_effect: ^2.2.3
  lottie: ^1.4.2

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env
